### ISSUE TITLE
missing osm attribution on traffic.bz.it

### ISSUE THREAD

**Issue by tyrasd** [tis-innovation-park/BZtraffic#1]
On [traffic.bz.it](http://traffic.bz.it/) there is a prominent map which is AFAICT based on OpenStreetMap data. OpenStreetMap requires an attribution whenever such a map is displayed (see http://www.openstreetmap.org/copyright). This copyright message is missing on the formerly mentioned map.

see also https://github.com/tis-innovation-park/realtimebus/issues/20

**Comment by ohnewein** [comment]
@ivanc can you fix this, like @bertolla did on bus.bz.it and bus.meran.eu ?
