### ISSUE TITLE
Add trend related to historical travel times

### ISSUE THREAD

**Issue by rcavaliere** [tis-innovation-park/BZtraffic#4]
As already planned in the design study, we should include in the trend plot not only the plot related to "today" but also a plot related to the average travel times related to the same day pattern (i.e. day of the week, presence of precipitation or not).

**Comment by ivanc** [comment]
at moment 2 different visualizations, are present, 
- today
- and average of the last 30 days
  the precipitation information was not present at the time of the design study, but we are  interesting   to implement it in a future release
